#include "math/functions/easing-function.h"
#include "math/interval.h"
#include "math/functions/easing/linear-easing-function.h"
#include "math/functions/easing/stretch-easing-function.h"
#include "math/functions/easing/bounce-easing-function.h"